server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://106.15.233.31:13306/nj?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  mybatis-plus:
      mapper-locations: classpath:mapper/*.xml
      # 控制台打印sql语句
      configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
